import fs from "node:fs";
import path from "node:path";
import { parseFrontMatter } from "../scripts/lib/frontmatter.mjs";
import { walkFiles } from "../scripts/lib/walk.mjs";

const ROOT = path.join(process.cwd(), "content", "sitemaps");
const EXTERNAL_SEARCH_SITEMAP_URL = "https://files.jcrt.org/metadata/search-sitemap.xml";
// Canonical index of every file the CDN serves (per-folder sitemaps under /sitemaps/).
const EXTERNAL_CDN_SITEMAP_INDEX_URL = "https://files.jcrt.org/sitemap.xml";
// A <sitemapindex> child must be a <urlset>. oai_dc.xml, doaj-archives.xml and
// datacite.xml are metadata payloads (<records>) with no <url> entries; Search Console
// rejects them as index children. They stay discoverable through the <link rel="alternate">
// tags in partials/head_static.njk and the /oai endpoint.
const EXCLUDED_FROM_MAIN_INDEX = new Set([
	"/sitemaps/sitemaps.xml",
	"/media-sitemap.xml",
	"/sitemaps/datacite.xml",
]);
const LOCAL_METADATA_SITEMAPS = [
	{ path: "/sitemaps/citations/ris-sitemap.xml", file: path.join("public", "sitemaps", "citations", "ris-sitemap.xml") },
	{ path: "/sitemaps/citations/csl-json-sitemap.xml", file: path.join("public", "sitemaps", "citations", "csl-json-sitemap.xml") },
];
// Intentionally empty. A <sitemapindex> entry must resolve to a <urlset> or a nested
// index; RSS feeds and /feed/twtxt.txt are neither, and listing them here made the root
// sitemap.xml unparseable as an index. Feeds are advertised via <link rel="alternate">.
const ALWAYS_INCLUDE_FEEDS = [];
const JCRT_FILES_METADATA = path.resolve(process.cwd(), "..", "jcrt-files", "metadata");

function toDateOnly(value) {
	const d = new Date(value);
	if (Number.isNaN(d.getTime())) return "";
	return d.toISOString().slice(0, 10);
}

function getFallbackLastmod() {
	return toDateOnly(new Date());
}

function getFileLastmodOrEmpty(filePath) {
	try {
		const stat = fs.statSync(filePath);
		return toDateOnly(stat.mtime);
	} catch {
		return "";
	}
}

/** Build the sitemap index: every content/sitemaps/*.xml.njk plus the CDN and citation sitemaps, deduplicated. */
export default function sitemapIndex() {
	const files = walkFiles(ROOT, { match: (name) => name.endsWith(".xml.njk") });

	const fallbackLastmod = getFallbackLastmod();
	const entries = [];
	for (const filePath of files) {
		const raw = fs.readFileSync(filePath, "utf8");
		const fm = parseFrontMatter(raw).data;
		const permalink = String(fm.permalink || "").trim();
		if (!permalink || !permalink.endsWith(".xml")) continue;
		if (EXCLUDED_FROM_MAIN_INDEX.has(permalink)) continue;
		let lastmod = "";
		try {
			const stat = fs.statSync(filePath);
			lastmod = toDateOnly(stat.mtime);
		} catch {
			lastmod = "";
		}
		entries.push({
			path: permalink,
			lastmod: lastmod || fallbackLastmod,
		});
	}

	// Always include the external search sitemap.
	// Its lastmod comes from the sibling `jcrt-files` checkout, which exists on a
	// maintainer's workstation but never on CI. Rather than assert today's date there —
	// which tells crawlers this sitemap changes every single day and wastes crawl budget —
	// omit <lastmod> entirely. It is an optional element, and the sitemaps.xml.njk
	// template already skips it when empty. An absent date is honest; a wrong one is not.
	const searchSitemapFile = path.join(JCRT_FILES_METADATA, "search-sitemap.xml");
	const searchSitemapLastmod = getFileLastmodOrEmpty(searchSitemapFile);
	if (!searchSitemapLastmod) {
		console.warn(
			`[sitemapIndex] ${searchSitemapFile} not found (expected on CI); omitting lastmod for ${EXTERNAL_SEARCH_SITEMAP_URL}`
		);
	}
	entries.push({
		loc: EXTERNAL_SEARCH_SITEMAP_URL,
		path: EXTERNAL_SEARCH_SITEMAP_URL,
		lastmod: searchSitemapLastmod,
	});

	// The CDN's own sitemap index. Its lastmod lives with the CDN (regenerated by its
	// deploy workflow), so none is asserted here — the template omits empty lastmods.
	entries.push({
		loc: EXTERNAL_CDN_SITEMAP_INDEX_URL,
		path: EXTERNAL_CDN_SITEMAP_INDEX_URL,
		lastmod: "",
	});

	// Always include local metadata sitemaps
	for (const ext of LOCAL_METADATA_SITEMAPS) {
		entries.push({
			path: ext.path,
			lastmod: getFileLastmodOrEmpty(path.resolve(process.cwd(), ext.file)) || fallbackLastmod,
		});
	}

	// philpapers.xml is an RSS feed, not a <urlset>, so it does not belong in a
	// <sitemapindex> either. Left out for the same reason as ALWAYS_INCLUDE_FEEDS.

	for (const feedPath of ALWAYS_INCLUDE_FEEDS) {
		entries.push({
			path: feedPath,
			lastmod: getFallbackLastmod(),
		});
	}

	const unique = new Map();
	for (const item of entries) {
		const key = item.loc || item.path;
		if (!unique.has(key)) unique.set(key, item);
	}
	return [...unique.values()].sort((a, b) => (a.loc || a.path).localeCompare(b.loc || b.path));
}
