import fs from "node:fs";
import path from "node:path";
import * as yaml from "js-yaml";

const ROOT = path.join(process.cwd(), "content", "sitemaps");
const EXTERNAL_SEARCH_SITEMAP_URL = "https://files.jcrt.org/metadata/search-sitemap.xml";
// Canonical index of every file the CDN serves (per-folder sitemaps under /sitemaps/).
const EXTERNAL_CDN_SITEMAP_INDEX_URL = "https://files.jcrt.org/sitemap.xml";
const PROTECTED_SITEMAPS = [
	"/sitemaps/oai_dc.xml",
	"/sitemaps/doaj-archives.xml"
];
const EXCLUDED_FROM_MAIN_INDEX = new Set([
	"/sitemaps/sitemaps.xml",
	"/media-sitemap.xml",
]);
const LOCAL_METADATA_SITEMAPS = [
	{ path: "/sitemaps/doaj-archives.xml", file: path.join("public", "sitemaps", "doaj-archives.xml") },
	{ path: "/sitemaps/oai_dc.xml", file: path.join("public", "sitemaps", "oai_dc.xml") },
	{ path: "/sitemaps/citations/ris-sitemap.xml", file: path.join("public", "sitemaps", "citations", "ris-sitemap.xml") },
	{ path: "/sitemaps/citations/csl-json-sitemap.xml", file: path.join("public", "sitemaps", "citations", "csl-json-sitemap.xml") },
];
// Intentionally empty. A <sitemapindex> entry must resolve to a <urlset> or a nested
// index; RSS feeds and /feed/twtxt.txt are neither, and listing them here made the root
// sitemap.xml unparseable as an index. Feeds are advertised via <link rel="alternate">.
const ALWAYS_INCLUDE_FEEDS = [];
const JCRT_FILES_METADATA = path.resolve(process.cwd(), "..", "jcrt-files", "metadata");

function walk(dir) {
	const out = [];
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const full = path.join(dir, entry.name);
		if (entry.isDirectory()) out.push(...walk(full));
		else if (entry.isFile() && entry.name.endsWith(".xml.njk")) out.push(full);
	}
	return out;
}

function parseFrontMatter(content) {
	if (!content.startsWith("---")) return {};
	const match = content.match(/^---\s*\n([\s\S]*?)\n---\s*(?:\n|$)/);
	if (!match) return {};
	try {
		return yaml.load(match[1]) || {};
	} catch {
		return {};
	}
}

function toDateOnly(value) {
	const d = new Date(value);
	if (Number.isNaN(d.getTime())) return "";
	return d.toISOString().slice(0, 10);
}

function getFallbackLastmod() {
	return toDateOnly(new Date());
}

function getFileLastmodOrEmpty(filePath) {
	try {
		const stat = fs.statSync(filePath);
		return toDateOnly(stat.mtime);
	} catch {
		return "";
	}
}

/**
 * Build the sitemap index, ensuring all sitemaps/feeds are included with no duplicates,
 * except for protected sitemaps/feeds (philpapers.xml, oai_dc.xml, doaj-archives.xml),
 * which are always included even if they would otherwise be deduplicated.
 */
export default function sitemapIndex() {
	let files = [];
	try {
		files = walk(ROOT);
	} catch {
		return [];
	}

	const fallbackLastmod = getFallbackLastmod();
	const entries = [];
	for (const filePath of files) {
		const raw = fs.readFileSync(filePath, "utf8");
		const fm = parseFrontMatter(raw);
		const permalink = String(fm.permalink || "").trim();
		if (!permalink || !permalink.endsWith(".xml")) continue;
		if (EXCLUDED_FROM_MAIN_INDEX.has(permalink)) continue;
		let lastmod = "";
		try {
			const stat = fs.statSync(filePath);
			lastmod = toDateOnly(stat.mtime);
		} catch {
			lastmod = "";
		}
		entries.push({
			path: permalink,
			lastmod: lastmod || fallbackLastmod,
		});
	}

	// Always include the external search sitemap.
	// Its lastmod comes from the sibling `jcrt-files` checkout, which exists on a
	// maintainer's workstation but never on CI. Rather than assert today's date there —
	// which tells crawlers this sitemap changes every single day and wastes crawl budget —
	// omit <lastmod> entirely. It is an optional element, and the sitemaps.xml.njk
	// template already skips it when empty. An absent date is honest; a wrong one is not.
	const searchSitemapFile = path.join(JCRT_FILES_METADATA, "search-sitemap.xml");
	const searchSitemapLastmod = getFileLastmodOrEmpty(searchSitemapFile);
	if (!searchSitemapLastmod) {
		console.warn(
			`[sitemapIndex] ${searchSitemapFile} not found (expected on CI); omitting lastmod for ${EXTERNAL_SEARCH_SITEMAP_URL}`
		);
	}
	entries.push({
		loc: EXTERNAL_SEARCH_SITEMAP_URL,
		path: EXTERNAL_SEARCH_SITEMAP_URL,
		lastmod: searchSitemapLastmod,
	});

	// The CDN's own sitemap index. Its lastmod lives with the CDN (regenerated by its
	// deploy workflow), so none is asserted here — the template omits empty lastmods.
	entries.push({
		loc: EXTERNAL_CDN_SITEMAP_INDEX_URL,
		path: EXTERNAL_CDN_SITEMAP_INDEX_URL,
		lastmod: "",
	});

	// Always include local metadata sitemaps
	for (const ext of LOCAL_METADATA_SITEMAPS) {
		entries.push({
			path: ext.path,
			lastmod: getFileLastmodOrEmpty(path.resolve(process.cwd(), ext.file)) || fallbackLastmod,
		});
	}

	// philpapers.xml is an RSS feed, not a <urlset>, so it does not belong in a
	// <sitemapindex> either. Left out for the same reason as ALWAYS_INCLUDE_FEEDS.

	for (const feedPath of ALWAYS_INCLUDE_FEEDS) {
		entries.push({
			path: feedPath,
			lastmod: getFallbackLastmod(),
		});
	}

	// Deduplicate, but allow protected sitemaps/feeds to appear even if duplicated
	const unique = new Map();
	for (const item of entries) {
		const key = item.loc || item.path;
		if (PROTECTED_SITEMAPS.includes(key)) {
			// Always allow protected sitemaps/feeds
			unique.set(key + "#protected", item);
		} else {
			if (!unique.has(key)) unique.set(key, item);
		}
	}
	return [...unique.values()].sort((a, b) => (a.loc || a.path).localeCompare(b.loc || b.path));
}
