import fs from "node:fs";
import path from "node:path";
import { parseFrontMatter } from "../scripts/lib/frontmatter.mjs";
import { walkFiles } from "../scripts/lib/walk.mjs";

const ROOT = path.join(process.cwd(), "content", "sitemaps");
// Canonical index of every file the CDN serves (per-folder sitemaps under /sitemaps/).
const EXTERNAL_CDN_SITEMAP_INDEX_URL = "https://files.jcrt.org/sitemap.xml";
// A <sitemapindex> child must be a <urlset>. oai_dc.xml, doaj-archives.xml and
// datacite.xml are metadata payloads (<records>) with no <url> entries; Search Console
// rejects them as index children. They stay discoverable through the <link rel="alternate">
// tags in partials/head_static.njk and the /oai endpoint.
const EXCLUDED_FROM_MAIN_INDEX = new Set([
	"/sitemaps/sitemaps.xml",
	"/media-sitemap.xml",
	"/sitemaps/datacite.xml",
	"/sitemaps/oai_dc.xml",
	"/sitemaps/doaj-archives.xml",
	// jats-sitemap.xml is a valid <urlset>, but it lists metadata-only XML records that
	// carry X-Robots-Tag: noindex (public/_headers). Google was filing all 771 of them
	// under "Crawled - currently not indexed"; they stay discoverable via rel=alternate.
	"/sitemaps/jats-sitemap.xml",
]);
// Built by content/sitemaps/oai-feeds.11ty.js from _data/oaiFeeds.js (valid <urlset>s).
const LOCAL_METADATA_SITEMAPS = ["/sitemaps/citations/ris-sitemap.xml", "/sitemaps/citations/csl-json-sitemap.xml"];
// Intentionally empty. A <sitemapindex> entry must resolve to a <urlset> or a nested
// index; RSS feeds and /feed/twtxt.txt are neither, and listing them here made the root
// sitemap.xml unparseable as an index. Feeds are advertised via <link rel="alternate">.
const ALWAYS_INCLUDE_FEEDS = [];

function toDateOnly(value) {
	const d = new Date(value);
	if (Number.isNaN(d.getTime())) return "";
	return d.toISOString().slice(0, 10);
}

function getFallbackLastmod() {
	return toDateOnly(new Date());
}

/** Build the sitemap index: every content/sitemaps/*.xml.njk plus the CDN and citation sitemaps, deduplicated. */
export default function sitemapIndex() {
	const files = walkFiles(ROOT, { match: (name) => name.endsWith(".xml.njk") });

	const fallbackLastmod = getFallbackLastmod();
	const entries = [];
	for (const filePath of files) {
		const raw = fs.readFileSync(filePath, "utf8");
		const fm = parseFrontMatter(raw).data;
		const permalink = String(fm.permalink || "").trim();
		if (!permalink || !permalink.endsWith(".xml")) continue;
		if (EXCLUDED_FROM_MAIN_INDEX.has(permalink)) continue;
		let lastmod = "";
		try {
			const stat = fs.statSync(filePath);
			lastmod = toDateOnly(stat.mtime);
		} catch {
			lastmod = "";
		}
		entries.push({
			path: permalink,
			lastmod: lastmod || fallbackLastmod,
		});
	}

	// The CDN's own sitemap index. Its lastmod lives with the CDN (regenerated by its
	// deploy workflow), so none is asserted here — the template omits empty lastmods.
	entries.push({
		loc: EXTERNAL_CDN_SITEMAP_INDEX_URL,
		path: EXTERNAL_CDN_SITEMAP_INDEX_URL,
		lastmod: "",
	});

	for (const sitemapPath of LOCAL_METADATA_SITEMAPS) {
		entries.push({ path: sitemapPath, lastmod: fallbackLastmod });
	}

	// philpapers.xml is an RSS feed, not a <urlset>, so it does not belong in a
	// <sitemapindex> either. Left out for the same reason as ALWAYS_INCLUDE_FEEDS.

	for (const feedPath of ALWAYS_INCLUDE_FEEDS) {
		entries.push({
			path: feedPath,
			lastmod: getFallbackLastmod(),
		});
	}

	const unique = new Map();
	for (const item of entries) {
		const key = item.loc || item.path;
		if (!unique.has(key)) unique.set(key, item);
	}
	return [...unique.values()].sort((a, b) => (a.loc || a.path).localeCompare(b.loc || b.path));
}
